language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: KZXUT7oJtxrxj6dUjkwdZYFg1YjmAXLnWnuyX7oiICLeM6NM4o7kJfHKeHqx5GTb9/u6ED7HilXMJmk9v6T2hpVh0hvs9VqueCNEGCwKxzBwx7tYm/To5AJ2su4H2duo1UsP6NYBgfFWvWUOhysdNrTf9pHJ5eAs6hpLsdO/nIEvSSlDkwnsyk2/ndcGVhBjztyR/cE2MPoqO7aoGT+ZR7MiHVirE43UFnIJIcWqtLX9LefVkVQ0VTw9EKmj4cHCB5XY9RoeZGbYCEwDZU4IyBQw8qsfudDUQoOO9P2v1xtwMaqF5Uvdr7M1tDPoW2IV1I3i9KRycw5rYu1MyuGtArXG20TpCOzDkWH8j83QPDO54uKNIitPViv76zT178Vl3jLTXqV7P0t2bAYjnsViVEPU4a4wA6JeZpvUvmM//FMWZO3SBwYmcm4BpYLb1hBGIxhsO3OmTIepZ46Glh+xT/+QQ+T7R0KILt8U5kNnYPT3O9rxCssNPgOBi55Ir0VaNtnWYnSVttwwpvv9/1WqdW/60QoezghMoBaglfRJnIFX8Xa0B96VOxMq4tAfR2KaqSi3+AuXsESbdpwt6irnUjoqzkETtZVqwaNUJSDHPJyd8YKyD3gT/TVrsey7HJTq1cDggugvkor+T5vfa40gEh1azBkV8FGrYHkGQAoygxI=
  app: warm-hamlet-90982
  on:
    repo: drewlara/blog-api-challenge
